spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-server:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ecom-app/protocol/openid-connect/certs