eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    root: INFO
    com.chirayu: TRACE
  file:
    name: logs/eureka-server.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7
server:
  port: 8761