spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: chirayu
    password: chirayu
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8083